### ISSUE TITLE
C-level functions probably don't free memory

### ISSUE THREAD

**Issue by vkapartzianis** [hadley/l1tf#5]
Calling `l1tf` repeatedly will eventually crash R. Try the following for example:

```
> library(l1tf)
> x <- runif(1e6)
> for (n in 1:1000) { y <- l1tf(x); rm(y); gc() }
```

I think that's because there are lots of `malloc` calls and not a single `free` one, in the C functions. I haven't verified it, though.

**Comment by twolodzko** [comment]
@vkapartzianis I wasn't able to reproduce it (on Windows machine). Could you post your system specs? 

Btw, @hadley are you planning to release this package on CRAN?

**Comment by hadley** [comment]
@twolodzko no plans in the short term

**Comment by twolodzko** [comment]
I was able to reproduce the bug on Linux machine.
