### ISSUE TITLE
Issue while installing install_github("hadley/l1tf") for R version R-3.4.2-win

### ISSUE THREAD

**Issue by gokulakrishnanp** [hadley/l1tf#6]
Hi hadley,

am getting this error. Error: running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 127 while installing using install_github. later it showing there is no library l1tf. Could you please help to resolve.

**Comment by hadley** [comment]
Should be fixed now
